spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  mail:
    host: 10.138.40.220
    port: 225
  redis:
    host: localhost
