spring:
  datasource:
    url: jdbc:mysql://10.138.228.244:3308/mailcenter?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mailcenter
    password: lF4%AqnOR2
  mail:
    host: 10.138.40.220
    port: 225
  # Redis.
  redis:
    # 配置格式变成了Duration类型
    timeout: 3000ms
    host: 10.135.16.164
    database: 2
    password: LIMITREE-dev
    port: 6386
